### ISSUE TITLE
 :state="errors[0] ? false : (valid ? true : null)"

### ISSUE THREAD

**Issue by julius-retzer** [TeachPlusPlus-Developers/TeachPlusPlus#18]
https://github.com/TeachPlusPlus-Developers/TeachPlusPlus/blob/4066e8eb88b2d247dad94ae1a2af587943da076e/themes/vuetober/src/components/inputs/BTextInputWithValidation.vue#L12

Z tohto vyrazu trosku boli hlava :D Treba checkovat aj `errors` aj `valid`? Ak su errors tak by som cakal ze valid bude false, ale mozno sa mylim.

**Comment by jakubkoje** [comment]
Treba chceckovat obidve. Ak necheckujem valid, tak input je hned oznaceny ako valid.

![image](https://user-images.githubusercontent.com/27420846/77069175-3920c700-69e8-11ea-9c64-0e7ca320005f.png)

**Comment by julius-retzer** [comment]
https://logaretm.github.io/vee-validate/guide/state.html#flags checkni toto, tu mozes zistit, ze ci user uz focusol input (touched). Na zaklade toho mozes zobrazit validaciu v spravny cas.

**Comment by jakubkoje** [comment]
#20 som už fixol, no toto už asi nezjednoduchším. Valid checkovať musím tak či tak.
