### ISSUE TITLE
new Promise

### ISSUE THREAD

**Issue by julius-retzer** [TeachPlusPlus-Developers/TeachPlusPlus#19]
https://github.com/TeachPlusPlus-Developers/TeachPlusPlus/blob/4066e8eb88b2d247dad94ae1a2af587943da076e/themes/vuetober/src/store/index.js#L42

Tu netreba vytvarat novy promise cez `new Promise` staci `return Axios(....)` a to uz je promise sam o sebe

**Comment by jakubkoje** [comment]
Neviem si predstaviť ako potom budem catchovat chybovu hlasku v komponente. 2x catch na jeden fetch nemoze byt ci?

**Comment by julius-retzer** [comment]
https://gist.github.com/wormyy/b96cac06c3504d66e236959a0201abd3

Skus takto, catch stale funguje. Ak potrebujes v componente pridat dalsi catch, tak stale mozes (tam ale asi podla mna uz netreba): `logout().then(...).catch(...)`

**Comment by julius-retzer** [comment]
Sorry, v tom giste som omylom nechal resolve a reject, takto by to malo byt:

``` logout({ commit, state }) {
      return Axios({ url: '/api/invalidate', data: { token: state.token }, method: 'POST' })
        .then((res) => {
          commit('logout');
        })
        .catch((err) => {
          commit('logout');
        });
    },

**Comment by julius-retzer** [comment]
Ak potrebujes pouzit este `res` napriklad v komponente, tak to musis returnut, co je vlastne to iste ako `resolve(res)`
```
 logout({ commit, state }) {
      return Axios({ url: '/api/invalidate', data: { token: state.token }, method: 'POST' })
        .then((res) => {
          commit('logout');
			return res;
        })
        .catch((err) => {
          commit('logout');
        });
    },

**Comment by jakubkoje** [comment]
Ja by som práveže potreboval dostať error v komponente aby som potom prípadne mohol cez router presmerovať používateľa alebo zobraziť chybové hlášku. Ale keď v store už ten catch raz mám tak potom mi už nefunguje catch v komponente. Ten promise to Aspoň čiastočne riešil.

**Comment by julius-retzer** [comment]
V tom pripade musis znovu "hodit" (:D) ten error a on sa bude dalej propagovat az do tvojho komponentu. To je vlastne to iste ako `reject(err)`

```
.catch((err) => {
     	commit('logout');
		throw err;
    });
