### ISSUE TITLE
Master 270 commitov za developm

### ISSUE THREAD

**Issue by julius-retzer** [TeachPlusPlus-Developers/TeachPlusPlus#65]
Preco mate aj master aj develop branche ked ocividne pouzivate len jednu z nich? Navrhoval by som pouzivat len master branch, alebo ked tak z nejakeho dovodu chcete aj aj, tak merginte develop raz za cas do masteru

**Comment by jakubkoje** [comment]
Jo, pozeral som na to. Je to useless.
