### ISSUE TITLE
User id

### ISSUE THREAD

**Issue by julius-retzer** [TeachPlusPlus-Developers/TeachPlusPlus#66]
https://github.com/TeachPlusPlus-Developers/TeachPlusPlus/blob/65e4ee6bc6e9eaef690e8ee77a9a3a6c9c810f0c/themes/vuetober/src/components/Teacher.vue#L103

Mat ID v konzistentnom formate a nekonvertovat zakazdym. Myslim ze sme sa uz o tom bavili. Vytvaram issue aby sa na to nezabudlo

**Comment by jakubkoje** [comment]
October vracia id usera ako int a id usera v feedbacku etc. dava ako string. Takze parsovaniu sa nevyhnem. Jedine to môžem dať normálne ako parseInt alebo iba ==(skôr to prvé).

**Comment by julius-retzer** [comment]
Tak mozno je na backande, ze jedno id je ukladane ako string a druhe ako int?
