### ISSUE TITLE
Odd css rule

### ISSUE THREAD

**Issue by julius-retzer** [TeachPlusPlus-Developers/TeachPlusPlus#67]
https://github.com/TeachPlusPlus-Developers/TeachPlusPlus/blob/65e4ee6bc6e9eaef690e8ee77a9a3a6c9c810f0c/themes/vuetober/src/components/Teacher.vue#L103

Toto je oddly specific, pouziva sa toto niekde?

**Comment by jakubkoje** [comment]
Není to css rule, zisťuje to či už user dal like na ten feedback. Ak áno zobrazí plne srdce, ak nie tak prázdne. Dá sa to spraviť asi aj jedným elementom, ale toho zisťovania či už user dal like na ten feedback sa nezbavím asi.

**Comment by julius-retzer** [comment]
Tam som chcel linkut uplne iny riadok, neviem preco sa mi tam dal tento z tej druhej issue :)

Uz sa mi to nechce hladat kde to bolo, tak nevadi :D aj tak to bolo minor
