### ISSUE TITLE
Class names by mali pouzivat `-`

### ISSUE THREAD

**Issue by julius-retzer** [TeachPlusPlus-Developers/TeachPlusPlus#68]
https://github.com/TeachPlusPlus-Developers/TeachPlusPlus/blob/65e4ee6bc6e9eaef690e8ee77a9a3a6c9c810f0c/themes/vuetober/src/views/Register.vue#L158

Zvycajne sa v classoch pouziva `-` na oddelovanie slov, nie `_`

**Comment by jakubkoje** [comment]
@MarkMucska kuk
